#!/usr/bin/env bash
# P0a — generate cloud-mode host_register variant for nexus.
#
# Generates `host_register_cloud.sh` that registers `host.akida-cloud-colfax`
# (ephemeral, secure-wipe-on-start) instead of `host.rpi5-akida` (persistent).
#
# Subcommands:
#   generate   write to xeno/scripts/d1_prep/host_register_cloud.sh (preview only)
#   apply      copy generated script to ~/core/nexus/scripts/akida/host_register_cloud.sh
#              (DEFERRED to D+0 09:00 KST per own 34 mandate-4)
set -euo pipefail
XENO_ROOT="${XENO_ROOT:-$HOME/core/xeno}"
NEXUS_ROOT="${NEXUS_ROOT:-$HOME/core/nexus}"
GENERATED="$XENO_ROOT/scripts/d1_prep/host_register_cloud.generated.sh"

cmd="${1:-generate}"
case "$cmd" in
  generate)
    cat > "$GENERATED" <<'GENEOF'
#!/usr/bin/env bash
# host_register_cloud.sh — register host.akida-cloud-colfax in ~/core/.workspace.
# Generated by xeno P0a 2026-05-08.
# Differs from host_register.sh:
#   - label: host.akida-cloud-colfax (NOT host.rpi5-akida)
#   - kind: ephemeral (secure-wipe per session, not persistent dev-kit)
#   - hardware_present: cloud (NOT physical AKD1000)
set -euo pipefail
WORKSPACE="${WORKSPACE:-$HOME/core/.workspace}"
EVIDENCE_DIR="${EVIDENCE_DIR:-state/akida_evidence}"
FORCE="${FORCE:-0}"

# Cloud session evidence: evidence files emitted DURING reservation slot
if [[ "$FORCE" != "1" ]]; then
  if ! ls "$EVIDENCE_DIR"/F-L1_*.json >/dev/null 2>&1; then
    echo "ERROR: no F-L1 evidence — fire energy_meter.py during cloud session first" >&2
    exit 2
  fi
fi

if [[ ! -f "$WORKSPACE" ]]; then
  echo "ERROR: workspace not found at $WORKSPACE" >&2
  exit 4
fi

if grep -q '^resource host\.akida-cloud-colfax ' "$WORKSPACE"; then
  echo "host.akida-cloud-colfax already registered — no-op (ephemeral; re-register on next reservation)"
  exit 0
fi

ANCHOR='^resource gpu\.h100 '
if ! grep -q "$ANCHOR" "$WORKSPACE"; then
  echo "ERROR: anchor 'resource gpu.h100' not found" >&2
  exit 5
fi

TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
TMP="$(mktemp)"
awk -v ts="$TS" '
  /^resource gpu\.h100 / { in_block=1 }
  in_block && /^$/ {
    print
    print "resource host.akida-cloud-colfax \"BrainChip Akida Cloud (Colfax hosted) — ephemeral neuromorphic edge-inference (~1W AKD1000, secure-wipe per session)\""
    print "  owner    xeno"
    print "  kind     ephemeral"
    print "  label    low-power-inference-cloud"
    print "  label    neuromorphic"
    print "  registered " ts
    in_block=0
    next
  }
  { print }
' "$WORKSPACE" > "$TMP"

if ! diff -q "$WORKSPACE" "$TMP" >/dev/null; then
  cp "$WORKSPACE" "$WORKSPACE.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  mv "$TMP" "$WORKSPACE"
  echo "registered host.akida-cloud-colfax in $WORKSPACE (backup written)"
else
  rm -f "$TMP"
  echo "ERROR: anchor matched but no insertion change" >&2
  exit 6
fi
GENEOF
    chmod +x "$GENERATED"
    echo "[P0a] generated: $GENERATED"
    echo "  apply during D+0 cloud session (NOT now — own 34 mandate-4 source repo untouched)"
    echo "  or: copy to $NEXUS_ROOT/scripts/akida/host_register_cloud.sh post-cycle"
    ;;
  apply)
    if [[ ! -f "$GENERATED" ]]; then echo "no generated — run: $0 generate" >&2; exit 1; fi
    target="$NEXUS_ROOT/scripts/akida/host_register_cloud.sh"
    if [[ -f "$target" ]]; then
      echo "ERROR: $target exists — manual review before overwrite" >&2
      exit 1
    fi
    cp "$GENERATED" "$target"
    chmod +x "$target"
    echo "[P0a] applied: $target"
    echo "  WARNING: own 34 mandate-4 says source repo untouched until D+1 close."
    echo "  This apply violates mandate-4 — confirm with user OR defer."
    ;;
  *) echo "usage: $0 {generate | apply}" >&2; exit 2 ;;
esac
